### ISSUE TITLE
ソースは公開されないのでしょうか？

### ISSUE THREAD

**Issue by eiryu** [kenji-namba/codic-eclipse-plugin#1]

**Comment by kenji-namba** [comment]
きたないソースだったので、公開してませんでしたｗ。もし、個人的に改変して使うのであれば、jarの中にソースが入っていたと思います。

**Comment by eiryu** [comment]
多分みんなが直してくれるので公開しましょう！！１

**Comment by kenji-namba** [comment]
eiryuさん
そうですね。また時間がある時にでも公開しますよ。

**Comment by kenji-namba** [comment]
ソース公開しました。何か問題がありましたら、orgに招待しますので一緒に修正しましょう ^^
https://github.com/codic-project/codic-eclipse-plugin

**Comment by eiryu** [comment]
ありがとうございます！
